#!/bin/bash

##### https://felixkratz.github.io/SketchyBar/features #####

# Load other files
source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

# aerospace setting
AEROSPACE_FOCUSED_MONITOR_NO=$(aerospace list-workspaces --focused)
AEROSPACE_LIST_OF_WINDOWS_IN_FOCUSED_MONITOR=$(aerospace list-windows --workspace $AEROSPACE_FOCUSED_MONITOR_NO | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')

##### Bar Appearance #####
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar

sketchybar --bar  position=top \
                  height=32 \
                  blur_radius=20 \
                  corner_radius=0 \
                  shadow=on \
                  sticky=on \
                  margin=0 \
                  y_offset=0 \
                  color=NULL \
                  border_color=NULL \
                  border_width=0

sketchybar --bar "${bar[@]}"

##### Changing Defaults #####
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:15.0"
  label.font="JetBrains Nerd Font:Bold:15.0"
  background.color=NULL
  background.corner_radius=7
  background.height=25
  label.padding_left=4
  label.padding_right=10
  icon.padding_left=10
  icon.padding_right=4
)

sketchybar --default "${default[@]}"

# --- Left Side Items ---
source $ITEM_DIR/apple.sh
# source $ITEM_DIR/spaces.sh
# source $ITEM_DIR/aerospace.sh
source $ITEM_DIR/front_app.sh

# --- Right Side Items ---
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/battery.sh
# source $ITEM_DIR/cpu.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/weather.sh
source $ITEM_DIR/media.sh

sketchybar --hotload on

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update

echo "sketchybar configuation loaded.."
